from typing import Callable


class GraphRenderer:
    def __init__(self):
        self.graph_data: list[float] = ...

        self.start_x: float = ...
        self.x_axit_value_func: Callable[[float, int], str] = ...

        self.width: int = ...
        self.height: int = ...

        self.left_blank: int = ...
        self.right_blank: int = ...
        self.top_blank: int = ...
        self.bottom_blank: int = ...

        self.inner_blank: int = ...

        self.graph_width: int = self.width - self.left_blank - self.right_blank
        self.graph_height: int = self.height - self.top_blank - self.bottom_blank
        self.graph_inner_height: int = self.graph_height - self.inner_blank * 2

        self.text_size: int = ...


        self.background_color: tuple[int, int, int] = ...
        self.foreground_color: tuple[int, int, int] = ...
        self.graph_color: tuple[int, int, int] = ...


        self.graph_min_value: float = min(self.graph_data)
        self.graph_max_value: float = min(self.graph_data)



    def graph_index_to_img_x(self, idx: int) -> int:
        x = self.left_blank
        x += self.graph_width / len(self.graph_data) * idx
        return x

    def graph_y_to_img_y(self, y: float) -> int:
        y -= self.graph_min_value
        y *= self.graph_inner_height / (self.graph_max_value - self.graph_min_value)

    def draw(self): ...

    def draw_graph(self):
        ...